name: .NET

on:
  push:
    branches: 
      - main
      - feauture


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore "./Muyi-Net-App"
    - name: Build code
      run: dotnet build "./Muyi-Net-App" --configuration Release --no-restore
    - name: Test code 
      run: dotnet test "./Muyi-Net-App" --no-restore --verbosity normal
    - name: Publish application
      run: dotnet publish "./Muyi-Net-App" -c Release -o Muyi-Net-App
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: "./Muyi-Net-App" 
      
